# This is a basic workflow to help you get started with Actions

name: Test Suite Run

# Controls when the workflow will run
on:
  pull_request:
  push:
    branches:
      - main
      - Production

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          ref: Production
          files: tests

      - name: Run the first file
        run: ls
#       - name: Run the second file
#         run: javac GameWindowTests.java
        
